Algoritmo "loop1a10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/09/2021
Var
// Seção de Declarações das variáveis 
   num : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   num <- 1
   enquanto num <= 10 faca
       escreva (num)
       num <- num + 1
   fimenquanto

Fimalgoritmo